apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-tls
spec:
  acme:
    email: fake@email.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-tls-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
